baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'Hua web'

[module]
  [[module.imports]]
    path = "github.com/hugo-sid/hugo-blog-awesome"

[[params.socialIcons]]
name = "github"
url = "https://github.com/chuahsieh"

[params]
  goToTop = true